import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Loader2, FileText, Download } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";

interface AIGeneratedReportProps {
  tradeIds?: string[];
  period?: "week" | "month" | "custom";
}

export const AIGeneratedReport = ({ tradeIds, period = "week" }: AIGeneratedReportProps) => {
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<any>(null);
  const [reportType, setReportType] = useState<"performance" | "analysis" | "coaching">("performance");

  const generateReport = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase.functions.invoke('ai-generate-report', {
        body: { 
          trade_ids: tradeIds,
          period,
          report_type: reportType
        }
      });

      if (error) throw error;

      setReport(data.report);
      toast.success("Report generated!");
    } catch (error: any) {
      if (error.message?.includes('429')) {
        toast.error("Rate limit exceeded. Please try again later.");
      } else if (error.message?.includes('402')) {
        toast.error("AI credits exhausted. Please add credits to continue.");
      } else {
        toast.error(error.message || "Failed to generate report");
      }
    } finally {
      setLoading(false);
    }
  };

  const downloadReport = () => {
    if (!report) return;

    const content = `
# AI Trading Report - ${new Date().toLocaleDateString()}

## Executive Summary
${report.summary}

## Key Findings
${report.findings.map((f: string) => `- ${f}`).join('\n')}

## Recommendations
${report.recommendations.map((r: string) => `- ${r}`).join('\n')}

## Detailed Analysis
${report.detailed_analysis}

---
Generated by Trading Journal Pro AI
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `trading-report-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Card className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="h-5 w-5 text-primary" />
          <h3 className="text-lg font-semibold">AI-Generated Report</h3>
        </div>
        {report && (
          <Button variant="outline" size="sm" onClick={downloadReport} className="gap-2">
            <Download className="h-4 w-4" />
            Download
          </Button>
        )}
      </div>

      <div className="flex gap-4">
        <Select value={reportType} onValueChange={(v: any) => setReportType(v)}>
          <SelectTrigger className="w-[200px]">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="performance">Performance Report</SelectItem>
            <SelectItem value="analysis">Deep Analysis</SelectItem>
            <SelectItem value="coaching">Coaching Report</SelectItem>
          </SelectContent>
        </Select>

        <Button onClick={generateReport} disabled={loading}>
          {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Generate Report"}
        </Button>
      </div>

      {report && (
        <div className="space-y-4">
          <div className="p-4 bg-muted rounded-lg">
            <h4 className="font-semibold mb-2">Executive Summary</h4>
            <p className="text-sm">{report.summary}</p>
          </div>

          <div>
            <h4 className="font-semibold mb-2">Key Findings</h4>
            <div className="space-y-2">
              {report.findings?.map((finding: string, idx: number) => (
                <div key={idx} className="flex items-start gap-2">
                  <Badge variant="outline" className="mt-0.5">{idx + 1}</Badge>
                  <p className="text-sm flex-1">{finding}</p>
                </div>
              ))}
            </div>
          </div>

          <div>
            <h4 className="font-semibold mb-2">Recommendations</h4>
            <div className="space-y-2">
              {report.recommendations?.map((rec: string, idx: number) => (
                <div key={idx} className="p-3 bg-primary/10 rounded-lg border border-primary/20">
                  <p className="text-sm">{rec}</p>
                </div>
              ))}
            </div>
          </div>

          {report.detailed_analysis && (
            <div>
              <h4 className="font-semibold mb-2">Detailed Analysis</h4>
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm whitespace-pre-wrap">{report.detailed_analysis}</p>
              </div>
            </div>
          )}
        </div>
      )}
    </Card>
  );
};
